url:     https://www.crablemedicalwriting.com

exclude:
  - scripts
  - README.md

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Services
   url: /services.html
 - title: Contact
   url: /contact.html
