safe:    false
baseurl: ""
url:     http://www.crablemedicalwriting.com

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Services
   url: /services.html
 - title: Contact
   url: /contact.html

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:     ['Gemfile', 'Gemfile.lock', 'Makefile', 'README.md']

future:    true
markdown:  rdiscount
permalink: date

rdiscount:
  extensions: [smart]
